#!/bin/bash
echo -e "\033[0;31m########TEST ls#######\033[0;37m"

echo -e "\033[0;34m>>>>>>>>>EXPECTED<<<<<<<<<\033[0;32m"
echo $(ls)
echo -e "\033[0;34m>>>>>>>>>>GOT<<<<<<<<<<<<\033[0;37m"
echo $(echo ls | ./shell2)

if [[ $(ls) =~ $(echo ls | ./shell2) ]]; then
	echo -e "\033[0;32m#THEY MATCH#\033[0;37m"
else
	echo "\033[0;31m#THEY DONT MATCH#\033[0;37m"
fi
echo -e "\033[0;31m########TEST ls WITH PATH########\033[0;37m"
echo -e "\033[0;34m>>>>>>>>>EXPECTED<<<<<<<<<\033[0;32m"
/bin/ls
echo -e "\033[0;34m>>>>>>>>>>GOT<<<<<<<<<<<<\033[0;37m"
echo "/bin/ls" | ./shell2
echo -e "\033[0;31m########TEST ls WITH SPACES########\033[0;37m"
   ls
echo -e "\033[0;31m#########TEST ls -la /tmp##########\033[0;37m"
ls -la /tmp
echo -e "\033[0;31m##########TEST ls -la /tmp WITH PATH#########\033[0;37m"
/bin/ls -la /tmp
echo -e "\033[0;31m##########TEST ls -l *c#########\033[0;37m"
echo -e "\033[0;31m##########SHOULD FAIL UNLESS HANDLING * WILDCARD#########\033[0;37m"
ls -l *c
